# Main config
esphome:
  name: bedroom_curtain
  platform: ESP8266
  board: nodemcuv2
  includes:
    - zemismart_curtain.h

substitutions:
  devicename: bedroom_curtain
  
logger:
  # level: INFO # ERROR/WARNING/INFO/DEBUG/VERBOSE/VERY_VERBOSE
  baud_rate: 0 # important because we are using uart0 to communicate with Tuya MCU

# Wireless config
wifi:
  ssid: !secret wifi_SSID
  password: !secret wifi_password
  # use_address: bedroom_curtain.local

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom Curtain"
    password: !secret default_password

captive_portal:

# Enable Home Assistant API and OTA update
api:
ota:

# ESP Status LED
status_led:
  pin:
    number: D4
    inverted: True
    
uart:
  - id: uart0
    tx_pin: GPIO01
    rx_pin: GPIO03
    baud_rate: 9600
    
cover:
  - platform: custom
    lambda: |-
      auto curtain = new CustomCurtain();
      App.register_component(curtain);
      return {curtain};
    covers:
      - name: $(devicename)
        device_class: blind

custom_component:
  - lambda: |-
      return { new CustomAPI() };

